"""
AI Task 1 - Cognitive Profiling Engine
Quiz questions generated by Groq.
Style detection from answers also by Groq.
"""
import json
from tools import ask_groq

SYSTEM_QUIZ = """You are an expert in cognitive learning styles.
Generate diagnostic quiz questions to detect how a student learns best.
CRITICAL: Respond ONLY with raw valid JSON. No markdown. No backticks. No extra text."""

SYSTEM_ANALYZE = """You are an expert in cognitive learning styles.
Analyze student quiz answers and detect their dominant learning style.
CRITICAL: Respond ONLY with raw valid JSON. No markdown. No backticks. No extra text."""


def _get_language_instruction(language: str) -> str:
    """Get language instruction for LLM prompts."""
    lang_map = {
        "en": "Respond in English.",
        "fr": "Respond in French. All content must be in French.",
        "ar": "Respond in Arabic. All content must be in Arabic."
    }
    return lang_map.get(language, "Respond in English.")


def get_quiz_questions(language: str = "en") -> list:
    """
    AI generates the diagnostic quiz questions dynamically.
    """
    lang_instruction = _get_language_instruction(language)
    
    prompt = f"""Generate 7 diagnostic quiz questions to detect a student's cognitive learning style.
The questions must reveal whether the student learns best through:
- visual    : diagrams, colors, spatial organization, slides
- narrative : stories, analogies, real-world examples
- logical   : step-by-step structure, formulas, rules
- auditory  : spoken explanation, conversation, reading aloud

{lang_instruction}

Return ONLY this exact JSON:
[
    {{
        "id": 1,
        "question": "the question text",
        "options": [
            "I prefer to use diagrams, charts, and visual maps to understand ideas",
            "I like to hear real-life stories and examples that relate to the topic",
            "I need clear step-by-step explanations with formulas and rules",
            "I learn best when someone explains it to me verbally"
        ]
    }}
]

Rules:
- Generate exactly 7 questions
- Each question must have exactly 4 options (NO letters like A, B, C, D)
- Each option must be a complete sentence describing HOW the student would learn
- Options must clearly map to one learning style (visual, narrative, logical, auditory)
- Questions must be relatable for students aged 14 to 20
- Never repeat the same question type
- Make questions natural and easy to answer"""

    text = ask_groq(SYSTEM_QUIZ, prompt, max_tokens=1500)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        clean = text.replace("```json", "").replace("```", "").strip()
        return json.loads(clean)


def analyze_style(quiz_answers: list, language: str = "en") -> dict:
    """
    AI Task 1 - Analyze answers and return cognitive profile JSON.
    This JSON is consumed directly by AI Task 2.
    """
    lang_instruction = _get_language_instruction(language)
    
    prompt = f"""
A student completed this diagnostic quiz:
{json.dumps(quiz_answers, indent=2)}

Each answer is a complete sentence describing how the student prefers to learn. Map them to learning styles:
- visual    : prefers diagrams, charts, visual maps, colors
- narrative : prefers stories, real-life examples, analogies
- logical   : prefers step-by-step explanations, formulas, rules
- auditory  : prefers verbal explanations, listening, discussion

{lang_instruction}

Return ONLY this exact JSON:
{{
    "style": "visual or narrative or logical or auditory",
    "confidence": 0.87,
    "secondary_style": "second closest style name",
    "description": "Two sentences explaining exactly how this student learns best.",
    "strengths": [
        "strength 1",
        "strength 2",
        "strength 3"
    ],
    "study_tips": [
        "actionable study tip 1",
        "actionable study tip 2",
        "actionable study tip 3"
    ],
    "avoid": "One sentence about what study methods do NOT work for this student."
}}
"""
    text = ask_groq(SYSTEM_ANALYZE, prompt, max_tokens=800)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        clean = text.replace("```json", "").replace("```", "").strip()
        return json.loads(clean)